import type { Metadata } from "next";
import { AppProps } from 'next/app';
import "../app/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps}  className="antialiased"/>;
}

export default MyApp;
